// Pure data tables for resource pricing and trading. Like the other config files, this file must
// NOT import anything, so any module can pull from it without circular imports.
//
// Moved out of resources.js, where they sat next to rendering code and were re-imported through
// resources.js by many other modules.

// Base market value per resource (used for trade/market pricing and stock values).
export const resource_values = {
    Food: 5,
    Lumber: 5,
    Chrysotile: 5,
    Stone: 5,
    Crystal: 6,
    Furs: 8,
    Copper: 25,
    Iron: 40,
    Aluminium: 50,
    Cement: 15,
    Coal: 20,
    Oil: 75,
    Uranium: 550,
    Steel: 100,
    Titanium: 150,
    Alloy: 350,
    Polymer: 250,
    Iridium: 420,
    Helium_3: 620,
    Deuterium: 950,
    Elerium: 2000,
    Water: 2,
    Neutronium: 1500,
    Adamantite: 2250,
    Infernite: 2750,
    Nano_Tube: 750,
    Graphene: 3000,
    Stanene: 3600,
    Bolognium: 9000,
    Vitreloy: 10200,
    Orichalcum: 99000,
    Asphodel_Powder: 249000,
    Horseshoe: 0,
    Nanite: 0,
    Genes: 0,
    Soul_Gem: 0,
    Corrupt_Gem: 0,
    Codex: 0,
    Cipher: 0,
    Demonic_Essence: 0,
    Blessed_Essence: 0
};

// Trade route ratio per resource (units moved per trade route).
export const tradeRatio = {
    Food: 20,
    Lumber: 20,
    Chrysotile: 10,
    Stone: 20,
    Crystal: 4,
    Furs: 10,
    Copper: 10,
    Iron: 10,
    Aluminium: 10,
    Cement: 10,
    Coal: 10,
    Oil: 5,
    Uranium: 1.2,
    Steel: 5,
    Titanium: 2.5,
    Alloy: 2,
    Polymer: 2,
    Iridium: 1,
    Helium_3: 1,
    Deuterium: 1,
    Elerium: 0.2,
    Water: 20,
    Neutronium: 0.5,
    Adamantite: 0.5,
    Infernite: 0.1,
    Nano_Tube: 1,
    Graphene: 1,
    Stanene: 1,
    Bolognium: 1.2,
    Vitreloy: 1.2,
    Orichalcum: 0.5
};
