import { loc } from './locale.js';
import { altRace } from './race_helpers.js';
import { global } from './vars.js';

// Bagian dari races (16 entri: nano .. ultra_sludge), dipisah dari races.js. Urutan entri sama persis.
export const racesPart3 = {
    nano: {
        name: loc('race_nano'),
        desc: loc('race_nano_desc'),
        type: 'synthetic',
        home: loc('race_nano_home'),
        entity: loc('race_nano_entity'),
        traits: {
            deconstructor: 1,
            linked: 1,
            shapeshifter: 1
        },
        solar: {
            red: loc('race_nano_solar_red'),
            hell: loc('race_nano_solar_hell'),
            gas: loc('race_nano_solar_gas'),
            gas_moon: loc('race_nano_solar_gas_moon'),
            dwarf: loc('race_nano_solar_dwarf'),
        },
        fanaticism: 'shapeshifter',
        basic(){ return false; }
    },
    ghast: {
        name: loc('race_ghast'),
        desc: loc('race_ghast_desc'),
        type: 'eldritch',
        home: loc('race_ghast_home'),
        entity: loc('race_ghast_entity'),
        traits: {
            dark_dweller: 1,
            swift: 1,
            anthropophagite: 1
        },
        solar: {
            red: loc('race_ghast_solar_red'),
            hell: loc('race_ghast_solar_hell'),
            gas: loc('race_ghast_solar_gas'),
            gas_moon: loc('race_ghast_solar_gas_moon'),
            dwarf: loc('race_ghast_solar_dwarf'),
        },
        fanaticism: 'swift',
        basic(){ return false; }
    },
    shoggoth: {
        name: loc('race_shoggoth'),
        desc: loc('race_shoggoth_desc'),
        type: 'eldritch',
        home: loc('race_shoggoth_home'),
        entity: loc('race_shoggoth_entity'),
        traits: {
            living_tool: 1,
            bloated: 1
        },
        solar: {
            red: loc('race_shoggoth_solar_red'),
            hell: loc('race_shoggoth_solar_hell'),
            gas: loc('race_shoggoth_solar_gas'),
            gas_moon: loc('race_shoggoth_solar_gas_moon'),
            dwarf: loc('race_shoggoth_solar_dwarf'),
        },
        fanaticism: 'living_tool',
        basic(){ return false; }
    },
    dwarf: {
        name: loc('race_dwarf'),
        desc: loc('race_dwarf_desc'),
        type: 'hybrid',
        hybrid: ['humanoid','small'],
        home: loc('race_dwarf_home'),
        entity: loc('race_dwarf_entity'),
        traits: {
            artisan: 1,
            stubborn: 1
        },
        solar: {
            red: loc('race_dwarf_solar_red'),
            hell: loc('race_dwarf_solar_hell'),
            gas: loc('race_dwarf_solar_gas'),
            gas_moon: loc('race_dwarf_solar_gas_moon'),
            dwarf: loc('race_dwarf_solar_dwarf'),
        },
        fanaticism: 'artisan',
        basic(){ return false; }
    },
    raccoon: {
        name: loc('race_raccoon'),
        desc: loc('race_raccoon_desc'),
        type: 'hybrid',
        hybrid: ['carnivore','herbivore'], // ['omnivore'],
        home: loc('race_raccoon_home'),
        entity: loc('race_raccoon_entity'),
        traits: {
            rogue: 1,
            untrustworthy: 1
        },
        solar: {
            red: loc('race_raccoon_solar_red'),
            hell: loc('race_raccoon_solar_hell'),
            gas: loc('race_raccoon_solar_gas'),
            gas_moon: loc('race_raccoon_solar_gas_moon'),
            dwarf: loc('race_raccoon_solar_dwarf'),
        },
        fanaticism: 'rogue',
        basic(){ return false; }
    },
    lichen: {
        name: loc('race_lichen'),
        desc: loc('race_lichen_desc'),
        type: 'hybrid',
        hybrid: ['plant','fungi'],
        home: loc('race_lichen_home'),
        entity: loc('race_lichen_entity'),
        traits: {
            living_materials: 1,
            unstable: 1
        },
        solar: {
            red: loc('race_lichen_solar_red'),
            hell: loc('race_lichen_solar_hell'),
            gas: loc('race_lichen_solar_gas'),
            gas_moon: loc('race_lichen_solar_gas_moon'),
            dwarf: loc('race_lichen_solar_dwarf'),
        },
        fanaticism: 'living_materials',
        basic(){ return false; }
    },
    wyvern: {
        name: loc('race_wyvern'),
        desc: loc('race_wyvern_desc'),
        type: 'hybrid',
        hybrid: ['avian','reptilian'],
        home: loc('race_wyvern_home'),
        entity: loc('race_wyvern_entity'),
        traits: {
            elemental: 1,
            chicken: 1
        },
        solar: {
            red: loc('race_wyvern_solar_red'),
            hell: loc('race_wyvern_solar_hell'),
            gas: loc('race_wyvern_solar_gas'),
            gas_moon: loc('race_wyvern_solar_gas_moon'),
            dwarf: loc('race_wyvern_solar_dwarf'),
        },
        fanaticism: 'elemental',
        basic(){ return false; }
    },
    beholder: {
        name: loc('race_beholder'),
        desc: loc('race_beholder_desc'),
        type: 'hybrid',
        hybrid: ['eldritch','giant'],
        home: loc('race_beholder_home'),
        entity: loc('race_beholder_entity'),
        traits: {
            ocular_power: 1,
            floating: 1
        },
        solar: {
            red: loc('race_beholder_solar_red'),
            hell: loc('race_beholder_solar_hell'),
            gas: loc('race_beholder_solar_gas'),
            gas_moon: loc('race_beholder_solar_gas_moon'),
            dwarf: loc('race_beholder_solar_dwarf'),
        },
        fanaticism: 'ocular_power',
        basic(){ return false; }
    },
    djinn: {
        name: loc('race_djinn'),
        desc: loc('race_djinn_desc'),
        type: 'hybrid',
        hybrid: ['sand','fey'],
        home: loc('race_djinn_home'),
        entity: loc('race_djinn_entity'),
        traits: {
            wish: 1,
            devious: 1
        },
        solar: {
            red: loc('race_djinn_solar_red'),
            hell: loc('race_djinn_solar_hell'),
            gas: loc('race_djinn_solar_gas'),
            gas_moon: loc('race_djinn_solar_gas_moon'),
            dwarf: loc('race_djinn_solar_dwarf'),
        },
        fanaticism: 'wish',
        basic(){ return false; }
    },
    narwhal: {
        name: loc('race_narwhal'),
        desc: loc('race_narwhal_desc'),
        type: 'hybrid',
        hybrid: ['aquatic','polar'],
        home: loc('race_narwhal_home'),
        entity: loc('race_narwhal_entity'),
        traits: {
            tusk: 1,
            blubber: 1
        },
        solar: {
            red: loc('race_narwhal_solar_red'),
            hell: loc('race_narwhal_solar_hell'),
            gas: loc('race_narwhal_solar_gas'),
            gas_moon: loc('race_narwhal_solar_gas_moon'),
            dwarf: loc('race_narwhal_solar_dwarf'),
        },
        fanaticism: 'tusk',
        basic(){ return false; }
    },
    bombardier: {
        name: loc('race_bombardier'),
        desc: loc('race_bombardier_desc'),
        type: 'hybrid',
        hybrid: ['insectoid','heat'],
        home: loc('race_bombardier_home'),
        entity: loc('race_bombardier_entity'),
        traits: {
            grenadier: 1,
            aggressive: 1
        },
        solar: {
            red: loc('race_bombardier_solar_red'),
            hell: loc('race_bombardier_solar_hell'),
            gas: loc('race_bombardier_solar_gas'),
            gas_moon: loc('race_bombardier_solar_gas_moon'),
            dwarf: loc('race_bombardier_solar_dwarf'),
        },
        fanaticism: 'grenadier',
        basic(){ return false; }
    },
    nephilim: {
        name: loc('race_nephilim'),
        desc: loc('race_nephilim_desc'),
        type: 'hybrid',
        hybrid: ['demonic','angelic'],
        home: loc('race_nephilim_home'),
        entity: loc('race_nephilim_entity'),
        traits: {
            empowered: 2,
            blasphemous: 1
        },
        solar: {
            red: loc('race_nephilim_solar_red'),
            hell: loc('race_nephilim_solar_hell'),
            gas: loc('race_nephilim_solar_gas'),
            gas_moon: loc('race_nephilim_solar_gas_moon'),
            dwarf: loc('race_nephilim_solar_dwarf'),
        },
        fanaticism: 'empowered',
        basic(){ return false; }
    },
    hellspawn: {
        name: loc('race_hellspawn'),
        desc: loc('race_hellspawn_desc'),
        type: 'demonic',
        home: loc('race_hellspawn_home'),
        entity: loc('race_hellspawn_entity'),
        traits: { immoral: 4 },
        solar: {
            red: loc('race_hellspawn_solar_red'),
            hell: loc('race_hellspawn_solar_hell'),
            gas: loc('race_hellspawn_solar_gas'),
            gas_moon: loc('race_hellspawn_solar_gas_moon'),
            dwarf: loc('race_hellspawn_solar_dwarf'),
        },
        fanaticism: 'immoral',
        basic(){ return false; }
    },
    junker: {
        name: altRace('junker') ? loc('race_ghoul') : loc('race_junker'),
        desc: altRace('junker') ? loc('race_ghoul_desc') : loc('race_junker_desc'),
        type: (function(){ return global.race.hasOwnProperty('jtype') ? global.race.jtype : 'humanoid'; })(),
        home: altRace('junker') ? loc('race_ghoul_home') : loc('race_junker_home'),
        entity: altRace('junker') ? loc('race_ghoul_entity') : loc('race_junker_entity'),
        traits: {
            diverse: 1,
            arrogant: 1,
            angry: 1,
            lazy: 1,
            paranoid: 1,
            greedy: 1,
            puny: 1,
            dumb: 1,
            nearsighted: 1,
            gluttony: 1,
            slow: 1,
            hard_of_hearing: 1,
            pessimistic: 1,
            solitary: 1,
            pyrophobia: 1,
            skittish: 1,
            nyctophilia: 1,
            frail: 1,
            atrophy: 1,
            invertebrate: 1,
            pathetic: 1,
            hibernator: 1,
            freespirit: 1,
            heavy: 1,
            gnawer: 1,
            hooved: 1
        },
        solar: {
            red: altRace('junker') ? loc('race_ghoul_solar_red') : loc('race_junker_solar_red'),
            hell: altRace('junker') ? loc('race_ghoul_solar_hell') : loc('race_junker_solar_hell'),
            gas: altRace('junker') ? loc('race_ghoul_solar_gas') : loc('race_junker_solar_gas'),
            gas_moon: altRace('junker') ? loc('race_ghoul_solar_gas_moon') : loc('race_junker_solar_gas_moon'),
            dwarf: altRace('junker') ? loc('race_ghoul_solar_dwarf') : loc('race_junker_solar_dwarf'),
        },
        fanaticism: 'none',
        basic(){ return false; }
    },
    sludge: {
        name: loc('race_sludge'),
        desc: loc('race_sludge_desc'),
        type: (function(){ return global.race.hasOwnProperty('jtype') ? global.race.jtype : 'humanoid'; })(),
        home: loc('race_sludge_home'),
        entity: loc('race_sludge_entity'),
        traits: {
            ooze: 0.25,
            diverse: 0.25,
            arrogant: 0.25,
            angry: 0.25,
            lazy: 0.25,
            hooved: 0.25,
            freespirit: 0.25,
            heavy: 0.25,
            gnawer: 0.25,
            paranoid: 0.25,
            greedy: 0.25,
            puny: 0.25,
            dumb: 0.25,
            nearsighted: 0.25,
            gluttony: 0.25,
            slow: 0.25,
            hard_of_hearing: 0.25,
            selenophobia: 0.25,
            pessimistic: 0.25,
            solitary: 0.25,
            pyrophobia: 0.25,
            skittish: 0.25,
            fragrant: 0.25,
            nyctophilia: 0.25,
            hibernator: 0.25,
            frail: 0.25,
            atrophy: 0.25,
            invertebrate: 0.25,
            unorganized: 0.25,
            slow_regen: 0.25,
            autoignition: 0.25,
            snowy: 0.25,
            mistrustful: 0.25,
            thalassophobia: 0.25,
            pathetic: 0.25,
            truthful: 0.25,
        },
        solar: {
            red: loc('race_sludge_solar_red'),
            hell: loc('race_sludge_solar_hell'),
            gas: loc('race_sludge_solar_gas'),
            gas_moon: loc('race_sludge_solar_gas_moon'),
            dwarf: loc('race_sludge_solar_dwarf'),
        },
        fanaticism: 'ooze',
        basic(){ return false; }
    },
    ultra_sludge: {
        name: loc('race_ultra_sludge'),
        desc: loc('race_ultra_sludge_desc'),
        type: (function(){ return global.race.hasOwnProperty('jtype') ? global.race.jtype : 'humanoid'; })(),
        home: loc('race_sludge_home'),
        entity: loc('race_sludge_entity'),
        traits: {
            ooze: 0.1,
            diverse: 0.1,
            arrogant: 0.1,
            angry: 0.1,
            lazy: 0.1,
            hooved: 0.1,
            freespirit: 0.1,
            heavy: 0.1,
            gnawer: 0.1,
            paranoid: 0.1,
            greedy: 0.1,
            puny: 0.1,
            dumb: 0.1,
            nearsighted: 0.1,
            gluttony: 0.1,
            slow: 0.1,
            hard_of_hearing: 0.1,
            selenophobia: 0.1,
            pessimistic: 0.1,
            solitary: 0.1,
            pyrophobia: 0.1,
            skittish: 0.1,
            fragrant: 0.1,
            nyctophilia: 0.1,
            hibernator: 0.1,
            frail: 0.1,
            atrophy: 0.1,
            invertebrate: 0.1,
            unorganized: 0.1,
            slow_regen: 0.1,
            autoignition: 0.1,
            snowy: 0.1,
            mistrustful: 0.1,
            thalassophobia: 0.1,
            pathetic: 0.1,
            truthful: 0.1,
            blubber: 0.25,
            aggressive: 0.25,
            devious: 0.25,
            floating: 0.25,
            blasphemous: 0.25,
            chicken: 0.25,
            unstable: 0.25,
            stubborn: 0.25,
            untrustworthy: 0.25,
            bloated: 0.25,
            dark_dweller: 0.25,
        },
        solar: {
            red: loc('race_sludge_solar_red'),
            hell: loc('race_sludge_solar_hell'),
            gas: loc('race_sludge_solar_gas'),
            gas_moon: loc('race_sludge_solar_gas_moon'),
            dwarf: loc('race_sludge_solar_dwarf'),
        },
        fanaticism: 'ooze',
        basic(){ return false; }
    },
};
